modLoader = "javafml"
loaderVersion = "[>=34,)"
license = "MIT"
issueTrackerURL = "https://github.com/Carloplayz/WindLaunch/issues"
displayName = "Wind Launch Mod"
authors = ["Carloplayz"]
description = """
A mod that automatically launches wind charges.
"""

[[mods]]
modId = "windlaunch"
version = "1.0.0"
displayName = "Wind Launch Mod"
description = "Automatically launches wind charges."
